Testing Enumerable Methods with RSpec
YuvrajM108/enumerable-methods pull request #3
Opened 2021-05-12 19:49 UTC by YuvrajM108

In this pull request we did the following:
- Initialized RSpec in our project.
- Set up a spec file for the project.
- Create RSpec test cases for all custom enumerable methods.
- Correct all linter errors.
- Edit README file.

2021-05-12 20:47 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi team!
Great job on this project:clap::clap:.** 

**Major highlights**

- The readme is very descriptive and professional
- The PR is also very descriptive

However, we just need to make a few changes to get the project approved:muscle:.

**To improve**

- [ ] Check my comments below and make the required changes.

Make the requested changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-05-12 20:47 UTC, enaburekhan commented on spec/enumerable_methods_spec.rb
> +  end
- [ ] Also, write tests for negative case scenarios for this `#my_each` method. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)) Example: there is a spec for correct usage of the method \[e.g. `it "creates object if all required attributes are passed"`\] and also there is spec for the wrong usage of a method \[e.g. `it "does not create the object if required attributes are missing"`\].

2021-05-12 20:47 UTC, enaburekhan commented on spec/enumerable_methods_spec.rb
> +      expect(%w[cat dog wombat].each_with_index do |item, index|
- [ ] Use the custom method `#my_each_with_index`. Currently, the regular ruby method is been used.
- [ ] Also, write tests for the negative case scenarios. An example already highlighted above

2021-05-12 20:47 UTC, enaburekhan commented on spec/enumerable_methods_spec.rb
> +  end
- [ ] Also, write tests for the negative case scenarios. An example already highlighted above

2021-05-12 20:47 UTC, enaburekhan commented on spec/enumerable_methods_spec.rb
> +  end
- [ ] Also, write tests for the negative case scenarios. An example already highlighted above

2021-05-12 22:14 UTC, YuvrajM108 commented on spec/enumerable_methods_spec.rb
> +  end
The only negative test scenario that I am seeing is when the method is called without a block. In this case, it is expected to return an enumerator. I am not able to find a way in which I can get the correct enumerator value to be placed into the parenthesis of eql.

2021-05-13 17:57 UTC, taiwo2 approved these changes
# Status: Approved 🎉 

Hey @YuvrajM108 , Good Job for implementing what the previous Code Reviewer requested. 
Your project is Approved and prepare for next project. Good luck

2021-05-13 19:08 UTC, merged